services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - php_data:/var/www/html # Volume nomeado para persistência de dados
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - redis
    networks:
      - app_network

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: erick
      MYSQL_DATABASE: bot
      MYSQL_USER: erick
      MYSQL_PASSWORD: erick
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data # Volume nomeado para persistência dos dados do Redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  php_data:
  redis_data:
