services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: erick
      MYSQL_DATABASE: bot
      MYSQL_USER: erick
      MYSQL_PASSWORD: erick
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
